export type HealthState='unknown'|'healthy'|'degraded'|'unhealthy'|'offline';
export type ControllerState='joining'|'active'|'draining'|'fenced'|'offline';
export type ConnectionPath='direct'|'peer_relay'|'relnet_relay';
export type UiState='loading'|'empty'|'offline'|'partial'|'degraded'|'blocked'|'error'|'retry'|'permission-denied'|'unsupported';
export type PlanSlug='free'|'pro'|'team'|'business';
export type SubscriptionState='unknown'|'inactive'|'trialing'|'active'|'past_due'|'canceled';
export interface FleetSnapshot{topologyGeneration:number;controllersOnline:number;nodesOnline:number;edgeServices:number;warnings:string[];readiness:HealthState;migrationStatus:'legacy'|'preparing'|'partial'|'ready'|'cutover'|'blocked'|'unknown'}
export interface ControllerSnapshot{id:string;name:string;state:ControllerState;health:HealthState;connectivity:HealthState;database:HealthState;placement:string|null;leaseName:string|null;generation:number|null;lastSeen:string|null;diagnostics:Record<string,unknown>|null}
export interface NodeSnapshot{name:string;deviceId:string;os:string;architecture:string;capabilities:string[];version:string|null;online:boolean|null;connectionMode:ConnectionPath|null;selectedGateway:string|null;subnetCapabilities:string[];health:HealthState;lastSeen:string|null}
export interface EdgeServiceSnapshot{kind:'stun'|'relay'|'gateway'|'exit'|'subnet';serviceIdentity:string;host:string;listeners:Array<{host:string;port:number;transport:'udp'|'tcp'}>;health:HealthState;draining:boolean;capacity:number|null;load:number|null;networkMapStatus:HealthState}
export interface NetworkSnapshot{direct:HealthState;relayFallback:HealthState;exitNodeSelection:string|null;gatewaySelection:string|null;subnetRouting:HealthState;internetEgress:HealthState;blockers:string[];networkMapGeneration:number|null;networkMapExpiresAt:string|null}
export interface AccessSnapshot{ssh:HealthState;terminal:HealthState;rdp:HealthState;reldrop:HealthState;relshare:HealthState;path:ConnectionPath|null;targetDeviceId:string|null;authorizationState:string|null}
export interface InstallationSnapshot{deviceId:string;installedVersion:string|null;targetVersion:string|null;operation:'install'|'update'|'repair'|'doctor'|'uninstall'|null;progress:number|null;errors:string[];rollbackReady:boolean|null}
export interface DiagnosticsSnapshot{localApi:HealthState;controlStream:HealthState;serviceStream:HealthState;networkMapGeneration:number|null;networkMapExpiresAt:string|null;relay:HealthState;ssh:HealthState;rdp:HealthState;reldrop:HealthState;relshare:HealthState}
export interface MigrationSnapshot{legacyState:HealthState;nextReadiness:HealthState;hostStatuses:Array<{host:string;state:string;blockers:string[]}>;blockers:string[];rollbackAvailable:boolean|null;cutoverStatus:'not-started'|'ready'|'in-progress'|'complete'|'blocked'|'unknown'}
export interface BillingSnapshot{spaceId:string;plan:PlanSlug;subscription:SubscriptionState;paidActive:boolean;periodEndsAt:string|null;source:'server'}
export interface AiEntitlementSnapshot{spaceId:string;plan:PlanSlug;included:boolean;monthlyCredits:number|null;pool:'space'|'team'|'contract';subscription:SubscriptionState;revenueGateOpen:boolean;source:'server'}
export interface AiUsageSnapshot{period:string;allocatedCredits:number|null;reservedCredits:number|null;consumedCredits:number|null;remainingCredits:number|null;source:'server'}
export interface ProductAiSnapshot{entitlement:AiEntitlementSnapshot;usage:AiUsageSnapshot;status:HealthState;blockers:string[]}
export interface RelNetConsoleSnapshot{fleet:FleetSnapshot;controllers:ControllerSnapshot[];nodes:NodeSnapshot[];edge:EdgeServiceSnapshot[];network:NetworkSnapshot;access:AccessSnapshot;installation:InstallationSnapshot[];diagnostics:DiagnosticsSnapshot;migration:MigrationSnapshot;billing:BillingSnapshot;ai:ProductAiSnapshot}
