'use client';
import { useCallback, useEffect, useState } from 'react';
import { Surface } from '@/app/components/Surface';

type Plan={slug:string;name:string;description:string;currency:string;monthly_price:number|null;yearly_price:number|null;self_service:boolean;public_sponsor_supported:boolean;limits:Record<string,number>;features:Record<string,boolean>};
type BillingState={requested_plan:string;effective_plan:string;status:string;customer_configured:boolean;subscription_configured:boolean;current_period_end:string|null;trial_end:string|null;cancel_at_period_end:boolean};
type BillingResponse={plan?:Plan;usage?:Record<string,number>;billing?:BillingState};
type Interval='monthly'|'yearly';

function money(value:number|null,currency='MXN'){return value==null?'Cotizar':new Intl.NumberFormat('es-MX',{style:'currency',currency,maximumFractionDigits:0}).format(value)}
function dateLabel(value:string|null|undefined){if(!value)return '—';const d=new Date(value);return Number.isNaN(d.getTime())?'—':new Intl.DateTimeFormat('es-MX',{dateStyle:'medium'}).format(d)}
function statusLabel(status:string){return ({active:'Activa',trialing:'En prueba',incomplete:'Pendiente de confirmación',incomplete_expired:'Checkout vencido',past_due:'Pago pendiente',unpaid:'Pago no cubierto',canceled:'Cancelada',free:'Free'} as Record<string,string>)[status]||'Estado no reconocido'}

export default function BillingPage(){
 const [plans,setPlans]=useState<Plan[]>([]);const [me,setMe]=useState<BillingResponse>({});const [csrf,setCsrf]=useState('');const [error,setError]=useState('');const [busy,setBusy]=useState('');const [loading,setLoading]=useState(true);const [returned,setReturned]=useState<'success'|'cancelled'|''>('');
 const loadBilling=useCallback(async()=>{setLoading(true);setError('');try{const s=await fetch('/console/api/session',{cache:'no-store'});if(s.status===401){location.replace('/console/login');return}if(!s.ok)throw new Error('No fue posible validar tu sesión.');setCsrf(String((await s.json()).csrf||''));const [p,m]=await Promise.all([fetch('/console/api/billing/plans',{cache:'no-store'}),fetch('/console/api/billing/me',{cache:'no-store'})]);if(!p.ok||!m.ok)throw new Error('No fue posible cargar la facturación.');setPlans((await p.json()).plans||[]);setMe(await m.json())}catch(e){setError(String(e instanceof Error?e.message:e))}finally{setLoading(false)}},[]);
 useEffect(()=>{const searchParams=new URLSearchParams(window.location.search);const state=searchParams.get('billing');if(state==='success'||state==='cancelled')setReturned(state);if(state||searchParams.has('session_id')){searchParams.delete('billing');searchParams.delete('session_id');const q=searchParams.toString();history.replaceState(null,'',`${location.pathname}${q?`?${q}`:''}${location.hash}`)}void loadBilling()},[loadBilling]);
 const billing=me.billing;const current=String(me.plan?.slug||billing?.effective_plan||'free');const authoritativePro=billing?.effective_plan==='pro'&&['active','trialing'].includes(billing.status);
 async function checkout(interval:Interval){setBusy(interval);setError('');try{const r=await fetch('/console/api/billing/checkout',{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-Token':csrf},body:JSON.stringify({plan_slug:'pro',interval})});const p=await r.json().catch(()=>({}));if(!r.ok)throw new Error(String(p.detail||'Checkout no disponible.'));const url=String(p.checkout_url||p.url||'');if(!url.startsWith('https://'))throw new Error('El proveedor no devolvió una URL de checkout segura.');location.assign(url)}catch(e){setError(String(e instanceof Error?e.message:e));setBusy('')}}
 async function portal(){setBusy('portal');setError('');try{const r=await fetch('/console/api/billing/portal',{method:'POST',headers:{'X-CSRF-Token':csrf}});const p=await r.json().catch(()=>({}));if(!r.ok)throw new Error(String(p.detail||'Portal no disponible.'));const url=String(p.portal_url||p.url||'');if(!url.startsWith('https://'))throw new Error('El proveedor no devolvió una URL de portal segura.');location.assign(url)}catch(e){setError(String(e instanceof Error?e.message:e));setBusy('')}}
 return <Surface eyebrow="Plan y facturación" title="Billing de tu Space, con estado autoritativo." description="Checkout y Portal se alojan en Stripe. Los entitlements sólo cambian después de confirmación autoritativa del backend.">
  {returned==='success'?<section className="card stack" role="status"><strong>Checkout finalizado; confirmación en curso.</strong><p className="helper">El redirect no activa Pro. Esta vista vuelve a consultar Billing y espera la confirmación autoritativa del webhook.</p></section>:null}
  {returned==='cancelled'?<section className="card stack" role="status"><strong>Checkout cancelado.</strong><p className="helper">Tu plan efectivo permanece según Billing. Puedes reintentar cuando quieras.</p></section>:null}
  {error?<div className="error" role="alert">{error} <button className="button secondary" onClick={()=>void loadBilling()}>Reintentar</button></div>:null}
  {loading?<section className="card"><p className="helper">Cargando estado de facturación…</p></section>:null}
  {!loading&&billing?<section className="card stack"><div className="actions"><span className="pill">Plan efectivo: {billing.effective_plan}</span><span className="pill">Suscripción: {statusLabel(billing.status)}</span></div><div className="grid-3"><div className="metric"><small>Plan solicitado</small><strong>{billing.requested_plan}</strong></div><div className="metric"><small>{billing.cancel_at_period_end?'Acceso hasta':'Renovación / periodo'}</small><strong>{dateLabel(billing.current_period_end)}</strong></div><div className="metric"><small>Portal</small><strong>{billing.customer_configured?'Disponible':'Después del primer checkout'}</strong></div></div>{billing.cancel_at_period_end?<p className="helper">La suscripción está marcada para cancelarse al final del periodo actual.</p>:null}{billing.customer_configured?<button className="button secondary" onClick={portal} disabled={Boolean(busy)}>{busy==='portal'?'Abriendo…':'Administrar facturación'}</button>:null}</section>:null}
  {!loading?<section className="grid-3"><div className="metric"><small>Nodos</small><strong>{me.usage?.nodes??0} / {me.plan?.limits?.max_nodes??0}</strong></div><div className="metric"><small>Usuarios permitidos</small><strong>{me.plan?.limits?.max_users??1}</strong></div><div className="metric"><small>RelDrop incluido</small><strong>{me.plan?.limits?.monthly_reldrop_gb??0} GB/mes</strong></div></section>:null}
  {!loading?<div className="grid-2">{plans.map(plan=><article className="card stack" key={plan.slug}><div><span className="pill">{plan.slug===current?'Plan actual':plan.self_service?'Self-service':'Venta asistida'}</span><h2>{plan.name}</h2><p className="helper">{plan.description}</p></div><div className="grid-2"><div className="metric"><small>Mensual</small><strong>{money(plan.monthly_price,plan.currency)}</strong></div><div className="metric"><small>Anual</small><strong>{money(plan.yearly_price,plan.currency)}</strong></div></div><div className="grid-3"><div className="metric"><small>Nodos</small><strong>{plan.limits.max_nodes}</strong></div><div className="metric"><small>Usuarios</small><strong>{plan.limits.max_users}</strong></div><div className="metric"><small>RelDrop</small><strong>{plan.limits.monthly_reldrop_gb} GB</strong></div></div><p className="helper">{plan.features.api_access?'API externa · ':''}{plan.features.remote_chrome?'Remote Chrome · ':''}{plan.features.automation?'Automatización · ':''}{plan.public_sponsor_supported?'Free admite patrocinio público.':'Sin anuncios del plan.'}</p>{plan.slug==='pro'&&plan.self_service&&current!=='pro'?<div className="actions"><button className="button primary" onClick={()=>checkout('monthly')} disabled={Boolean(busy)}>{busy==='monthly'?'Abriendo…':`Pro mensual · ${money(plan.monthly_price,plan.currency)}`}</button><button className="button secondary" onClick={()=>checkout('yearly')} disabled={Boolean(busy)}>{busy==='yearly'?'Abriendo…':`Pro anual · ${money(plan.yearly_price,plan.currency)}`}</button></div>:null}{!plan.self_service&&plan.slug!==current?<a className="button secondary" href="https://relead.com.mx" target="_blank" rel="noreferrer">Hablar con ReLead</a>:null}</article>)}</div>:null}
  {authoritativePro?<section className="card stack"><span className="pill">Pro confirmado</span><h2>Continúa con el onboarding de Pro</h2><p className="helper">Tu entitlement Pro ya fue confirmado por Billing. Configura automatización, Remote Chrome o enrola tu primer nodo desde Console.</p><a className="button primary" href="/console/">Configurar Pro</a></section>:null}
  <p className="helper" style={{marginTop:18}}>Los cobros sólo se inician desde Stripe Checkout. Team y Business permanecen como venta asistida conforme al contrato comercial vigente.</p>
 </Surface>
}
