import { BACKEND_DEPENDENCIES } from './relnet-api.js';

export const RELNET_NEXT_ROUTES=Object.freeze(['/console/relnet','/console/relnet/controllers','/console/relnet/nodes','/console/relnet/edge','/console/relnet/network','/console/relnet/installation','/console/relnet/diagnostics','/console/relnet/migration','/console/relnet/ai']);
export const UI_STATES=Object.freeze(['loading','empty','offline','partial','degraded','blocked','error','retry','permission-denied','unsupported']);
const NAV=[['Fleet','/console/relnet'],['Controllers','/console/relnet/controllers'],['Nodes','/console/relnet/nodes'],['Edge','/console/relnet/edge'],['Network','/console/relnet/network'],['Installation','/console/relnet/installation'],['Diagnostics','/console/relnet/diagnostics'],['Migration','/console/relnet/migration'],['AI-Coordinator','/console/relnet/ai']];
const UNKNOWN='<span class="valueUnknown">Sin endpoint</span>';
const dep=id=>BACKEND_DEPENDENCIES.find(x=>x.id===id);
const esc=v=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
export function isRelnetNextRoute(path){return RELNET_NEXT_ROUTES.includes(path.replace(/\/$/,'')||'/')}
function dependency(id){const d=dep(id);return `<div class="dependency" role="status"><strong>Backend pendiente · ${esc(id)}</strong><span>Backend dependency: ${esc(d?.method||'GET')} ${esc(d?.path||'sin ruta')}. Baseline 6838b2fa no expone este endpoint; no se simula éxito.</span></div>`}
function kv(rows){return `<ul class="list">${rows.map(([k,v])=>`<li><span>${k}</span><span>${v}</span></li>`).join('')}</ul>`}
function metric(t){return `<article class="card metric span4"><span class="kicker">${t}</span><strong>${UNKNOWN}</strong><small>Backend dependency</small></article>`}
function actions(labels,id){return `<div class="actions">${labels.map(x=>`<button class="button" type="button" disabled title="Backend pendiente: ${id}">${x}</button>`).join('')}</div>`}
function fleet(){return `<section class="grid">${['Topology generation','Controllers online','Nodes online','Edge services','Warnings','Readiness'].map(metric).join('')}<article class="card span8"><span class="kicker">Fleet</span><h2>Estado global</h2>${kv([['Migration status',UNKNOWN],['NetworkMap',UNKNOWN],['Active-active',UNKNOWN],['Blockers',UNKNOWN]])}${dependency('fleet.read')}</article><article class="card span4"><h2>Control plane</h2><p>Placement determinista entre Controllers elegibles; RelNet Next no define primary/secondary.</p><p class="contractNote">Controller fleet + Control Stream + NetworkMap v1.</p><h3>Operational contracts</h3><p>Service Stream: SSH · RDP · RelDrop · RelShare. Migration preserves rollback. AI model readiness includes GGUF status without assuming provisioning.</p></article></section>`}
function controllers(){return `<section class="grid"><article class="card span12"><span class="kicker">Controllers</span><h2>Controller A · Controller B · active-active</h2><div class="tableWrap"><table><caption>Controller fleet</caption><thead><tr><th>Controller</th><th>Health</th><th>Connectivity</th><th>DB</th><th>Placement</th><th>Lease / generation</th><th>Last seen</th></tr></thead><tbody>${['Controller A','Controller B'].map(n=>`<tr><td>${n}</td><td>${UNKNOWN}</td><td>${UNKNOWN}</td><td>${UNKNOWN}</td><td>${UNKNOWN}</td><td>${UNKNOWN}</td><td>${UNKNOWN}</td></tr>`).join('')}</tbody></table></div>${actions(['Drain','Diagnostics'],'controllers.drain')}${dependency('controllers.read')}</article></section>`}
function nodes(){return `<section class="grid"><article class="card span12"><span class="kicker">Nodes</span><h2>Endpoint inventory</h2><div class="tableWrap"><table><caption>RelNet Next nodes</caption><thead><tr><th>Node</th><th>Device ID</th><th>OS / architecture</th><th>Capabilities</th><th>Version</th><th>Online</th><th>Connection mode direct/relay</th><th>Selected gateway</th><th>Subnet capabilities</th><th>Health</th><th>Last seen</th></tr></thead><tbody><tr><td colspan="11">Sin datos: backend pendiente.</td></tr></tbody></table></div>${dependency('nodes.read')}</article></section>`}
function edge(){return `<section class="grid">${['STUN','Relay','Gateway'].map(k=>`<article class="card span4"><span class="kicker">Edge</span><h2>${k}</h2>${kv([['Service identity',UNKNOWN],['Host',UNKNOWN],['Listeners',UNKNOWN],['Health',UNKNOWN],['Drain',UNKNOWN],['Capacity',UNKNOWN],['Load',UNKNOWN],['NetworkMap status',UNKNOWN]])}</article>`).join('')}<article class="card span12">${dependency('edge.read')}</article></section>`}
function network(){return `<section class="grid"><article class="card span8"><span class="kicker">Network</span><h2>Path selection y egress</h2>${kv([['Direct',UNKNOWN],['Relay fallback',UNKNOWN],['Exit Node selection',UNKNOWN],['Gateway selection',UNKNOWN],['Subnet routing',UNKNOWN],['Internet egress',UNKNOWN],['Status and blockers',UNKNOWN]])}${dependency('network.read')}</article><article class="card span4"><span class="kicker">Frozen order</span><h2>Connectivity preference</h2><ol><li>Direct P2P</li><li>Approved Peer Relay</li><li>RelNet Relay fallback</li></ol><p>Gateway/Exit y Relay son capacidades separadas.</p></article><article class="card span12"><h3>NetworkMap</h3>${kv([['Topology generation',UNKNOWN],['Expiry',UNKNOWN],['NetworkMap status',UNKNOWN]])}</article></section>`}
function installation(){return `<section class="grid"><article class="card span8"><span class="kicker">Installation</span><h2>Lifecycle</h2>${kv([['Installed version',UNKNOWN],['Target version',UNKNOWN],['Operation progress',UNKNOWN],['Errors',UNKNOWN],['Rollback readiness',UNKNOWN]])}${actions(['Install','Update','Repair','Doctor','Uninstall'],'installation.action')}${dependency('installation.read')}</article><article class="card span4"><h2>Fail-closed</h2><p>Los planners del baseline no son un adaptador operativo de package/service. Las mutaciones están deshabilitadas mientras no exista endpoint y autorización.</p></article></section>`}
function diagnostics(){const rows=[['Local API','Unix socket / Named Pipe'],['Control Stream','heartbeat · health · NetworkMap'],['Service Stream','direct · peer_relay · relnet_relay'],['NetworkMap generation / expiry','signed map'],['Relay','Edge descriptor'],['SSH','service stream'],['RDP','service stream'],['RelDrop','service stream'],['RelShare','service stream']];return `<section class="grid"><article class="card span12"><span class="kicker">Diagnostics</span><h2>Cross-plane diagnostics</h2><div class="tableWrap"><table><caption>Diagnostic surfaces</caption><thead><tr><th>Surface</th><th>Status</th><th>Contract</th></tr></thead><tbody>${rows.map(([n,c])=>`<tr><td>${n}</td><td>${UNKNOWN}</td><td>${c}</td></tr>`).join('')}</tbody></table></div>${dependency('diagnostics.read')}</article></section>`}
function migration(){return `<section class="grid"><article class="card span12"><span class="kicker">Migration</span><h2>Legacy RelNet → RelNet Next</h2><div class="flow"><div class="flowNode"><strong>Legacy RelNet</strong>${kv([['Current legacy state',UNKNOWN],['Host migration status',UNKNOWN]])}</div><div class="flowArrow" aria-hidden="true">→</div><div class="flowNode"><strong>RelNet Next</strong>${kv([['Next readiness',UNKNOWN],['Cutover status',UNKNOWN]])}</div></div>${kv([['Blockers',UNKNOWN],['Rollback availability',UNKNOWN]])}${dependency('migration.read')}<p class="contractNote">No existe control de purge. Cualquier retiro de Legacy requiere autorización explícita y evidencia de rollback.</p></article></section>`}
const AI_FACTS=[['Hostname','AI-Coordinator'],['Tailscale','100.65.98.26'],['OS','Ubuntu 26.04'],['Architecture','x86_64'],['CPU','4 vCPU'],['RAM','7.6 GiB'],['Disk','~70 GiB libres'],['GPU','NVIDIA: none']];
function ai(){return `<section class="grid"><article class="card span12"><span class="kicker">AI</span><h2>AI-Coordinator</h2><p>Inventario declarado por coordinación; no es telemetría live.</p><div class="factGrid">${AI_FACTS.map(([k,v])=>`<div class="fact"><small>${k}</small><strong>${v}</strong></div>`).join('')}</div></article><article class="card span8"><h2>Runtime / model</h2>${kv([['Online/offline',UNKNOWN],['Health',UNKNOWN],['CPU usage',UNKNOWN],['RAM usage',UNKNOWN],['Disk telemetry',UNKNOWN],['Worker status',UNKNOWN],['Assigned jobs',UNKNOWN],['Model status',UNKNOWN],['GGUF provisioned yes/no',UNKNOWN],['Model name',UNKNOWN],['SHA',UNKNOWN],['Quantization',UNKNOWN],['Model architecture',UNKNOWN],['Context',UNKNOWN],['RAM requirement',UNKNOWN],['Benchmark',UNKNOWN],['Tokens/sec',UNKNOWN],['Readiness',UNKNOWN],['Error state',UNKNOWN]])}${dependency('ai.read')}</article><article class="card span4"><h2>Known constraint</h2><p>GPU NVIDIA: none. Sin endpoint autoritativo no se asume GGUF, modelo, benchmark ni tokens/sec.</p></article></section>`}
const VIEWS={controllers,nodes,edge,network,installation,diagnostics,migration,ai};
function keyFor(path){const p=path.replace(/\/$/,'');return p==='/console/relnet'?'fleet':p.split('/').at(-1)}
function states(){return `<details class="card span12"><summary>UI state contract</summary><div class="stateGrid" aria-live="polite">${UI_STATES.map(s=>`<div class="stateItem" data-ui-state="${s}">${s}</div>`).join('')}</div><form method="get" class="actions"><button class="button" type="submit" data-retry>Reintentar</button></form></details>`}
export function renderRelnetConsole(pathname){const clean=pathname.replace(/\/$/,'');const key=keyFor(clean);const title=key==='fleet'?'Fleet':NAV.find(([,h])=>h===clean)?.[0]||'RelNet Next';const body=key==='fleet'?fleet():(VIEWS[key]?.()||fleet());const nav=NAV.map(([label,href])=>`<a href="${href}"${href===clean?' aria-current="page"':''}>${label}</a>`).join('');return `<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>${title} · RelNet Next Console</title><link rel="stylesheet" href="/console/relnet/assets/ui.css"></head><body><a class="skip" href="#main-content">Saltar al contenido</a><div class="app"><aside class="sidebar"><div class="brand"><span class="mark">R</span><span><strong>RelNet Next</strong><small>Console</small></span></div><nav class="nav" aria-label="RelNet Next navigation">${nav}</nav><div class="sidebarFoot"><small>Backend contract</small><strong>6838b2fa</strong><small>UI fail-closed</small></div></aside><div class="workspace"><header class="topbar"><div class="breadcrumbs"><span>Console</span><span>/</span><strong>${title}</strong></div><div class="topmeta"><span class="badge">Backend pendiente</span><span>console.relead.com.mx</span></div></header><main class="content" id="main-content"><div class="hero"><div><span class="eyebrow">Authenticated operations</span><h1>${title}</h1><p>Observabilidad y controles de RelNet Next sin lógica de networking en la UI. Los valores dinámicos permanecen vacíos hasta que exista un endpoint autoritativo.</p></div></div>${body}<section class="grid">${states()}</section></main><footer class="footer">ReLead · RelNet Next Console · baseline 6838b2fa375a36a5a2806acc842f115bb69f2061</footer></div></div></body></html>`}
